spring.application.name=Springboot-API-REST
server.port=8081
spring.web.allow-cors=true

# Configuración de la base de datos MySQL en AWS RDS
spring.datasource.url=jdbc:mysql://db:3306/db_despacho?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root_password
spring.jpa.hibernate.ddl-auto=update

# Configuraci�n de Hibernate
spring.jpa.database=mysql
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html