services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_despacho
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 350M # Limita el consumo de MySQL para evitar fugas de memoria
    networks:
      - network-innovatech

  backend:
    image: 410397845770.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-repo:latest
    container_name: innovatech-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_despacho?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Forzamos a la Máquina Virtual de Java a restringir su consumo máximo de memoria RAM
      JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -Xmx300m"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 350M # Evita que Spring Boot sobrepase el límite asignado
    networks:
      - network-innovatech

  frontend:
    image: 410397845770.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend-repo:latest
    container_name: innovatech-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 100M # Nginx es sumamente liviano, 100M es más que suficiente
    networks:
      - network-innovatech

volumes:
  mysql_data:

networks:
  network-innovatech:
    driver: bridge